#server:
#  port: 10002
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/everywhere?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: Eminem0000
#  # 分布式配置
#  cloud:
#    nacos:
#      server-addr: localhost:8848
#      discovery:
#        namespace: 587a7d4d-c64f-41cc-b029-5eb7967c9ded
#  application:
#    name: everywhere-user
