#elasticsearch
server:
  port: 8085
spring:
  application:
    name: trip-search-server
  elasticsearch:
    rest:
      uris: http://localhost:9200
  main:
    allow-bean-definition-overriding: true  #多个feign接口可以指向同一个微服务

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

