server:
  port: 8083

spring:
  application:
    name: trip-data-server
  main:
    allow-bean-definition-overriding: true  #多个feign接口可以指向同一个微服务


  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848



