server:
  port: 8081
spring:
  application:
    name: trip-member-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/everywhere?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: Eminem0000

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        enabled: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


sms:
  url: https://way.jd.com/chuangxin/dxjk?mobile={0}&content=【创信】你的验证码是：{1}，3分钟内有效！&appkey={2}
  appkey: dd1f7d99cd632060789a56cfaa3b77ce
